### ISSUE TITLE
Замечания по заданию 5

### ISSUE THREAD

**Issue by dzheltkov** [UdalovaES/Poly_class_HW#1]
1) Сложные объекты (std::vector, Polynom) в функции стоит передавать по константной ссылке, а не копируя.

2) Необходимо добавить парсинг ввода.

**Comment by UdalovaES** [comment]
Исправила замечания

**Comment by dzheltkov** [comment]
`std::vector` в функцию `calculate` и `std::string` в функцию `get_actions` и конструктор `Polynom` тоже стоит передавать по константной ссылке (возможно что-то ещё пропустил, посмотрите сами, в целом всё, кроме базовых типов, стоит передавать по констанстной ссылке, если используется только для чтения).

**Comment by UdalovaES** [comment]
Внесла соответствующие изменения

**Comment by dzheltkov** [comment]
Задание зачтено.
